// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using LuxuryVilaManagement.Infrastructure.Data;

#nullable disable

namespace LuxuryVilaManagement.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDBContext))]
    [Migration("20251229175637_addAmenityToDB")]
    partial class addAmenityToDB
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("LuxuryVilaManagement.Domain.Entities.Amenity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("VilaId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("VilaId");

                    b.ToTable("Amenities");
                });

            modelBuilder.Entity("LuxuryVilaManagement.Domain.Entities.Vila", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Occupancy")
                        .HasColumnType("int");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<int>("Sqft")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Vilas");
                });

            modelBuilder.Entity("LuxuryVilaManagement.Domain.Entities.VilaNumber", b =>
                {
                    b.Property<int>("Vila_Number")
                        .HasColumnType("int");

                    b.Property<string>("SpecialDetails")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("VilaId")
                        .HasColumnType("int");

                    b.HasKey("Vila_Number");

                    b.HasIndex("VilaId");

                    b.ToTable("VilaNumbers");

                    b.HasData(
                        new
                        {
                            Vila_Number = 101,
                            VilaId = 1
                        },
                        new
                        {
                            Vila_Number = 102,
                            VilaId = 1
                        },
                        new
                        {
                            Vila_Number = 103,
                            VilaId = 1
                        });
                });

            modelBuilder.Entity("LuxuryVilaManagement.Domain.Entities.Amenity", b =>
                {
                    b.HasOne("LuxuryVilaManagement.Domain.Entities.Vila", "Vila")
                        .WithMany()
                        .HasForeignKey("VilaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Vila");
                });

            modelBuilder.Entity("LuxuryVilaManagement.Domain.Entities.VilaNumber", b =>
                {
                    b.HasOne("LuxuryVilaManagement.Domain.Entities.Vila", "Vila")
                        .WithMany()
                        .HasForeignKey("VilaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Vila");
                });
#pragma warning restore 612, 618
        }
    }
}
